### ISSUE TITLE
Allow namespace to be specified in values file

### ISSUE THREAD

**Issue by pdmars** [stardog-union/helm-charts#30]
Currently we deploy stardog into the helm release namespace. However, for users that have stardog as a dependency to another application and want it to run in its own namespace, they need to be able to override which namespace Stardog is deployed into so we should allow that via an option that can be set.

**Comment by pdmars** [comment]
The ZooKeeper chart defaults to the .Release.Namespace so that will need to be fixed downstream.

**Comment by danielburrell** [comment]
> The ZooKeeper chart defaults to the .Release.Namespace so that will need to be fixed downstream.

That's fine, I see https://github.com/stardog-union/helm-charts/issues/21 is open, I'll follow up with bitnami about sub-chart namespaces.

**Comment by danielburrell** [comment]
Zookeeper PR is out. https://github.com/bitnami/charts/pull/3881 though I know at this current time you're not using bitnami yet
