### ISSUE TITLE
Failed PR

### ISSUE THREAD

**Issue by MrMunki** [stardog-union/helm-charts#65]
Hi, I've tried a PR but the test is failing, not sure why as this wasn't changed. Could someone take a look?

https://github.com/stardog-union/helm-charts/pull/64 

Thanks,

D

**Comment by pdmars** [comment]
The tests just had a bit of a race condition which should be addressed on develop. If you rebase and rerun the tests it should be fixed.

**Comment by MrMunki** [comment]
Thanks for that, it's passed the test now :)
