### ISSUE TITLE
The stardog server was working fine for us previously, suddenly it's went down

### ISSUE THREAD

**Issue by sahoorajashree** [stardog-union/helm-charts#81]
We are using stardog application- URL through virtual service deployment in our project, it was working properly but suddenly went down in all environments.

**Comment by mhgrove** [comment]
@sahoorajashree it sounds like you are looking for Stardog support? This is an issue tracker for some open source software related to our product, not our product support forum. Our [docs have more information](https://docs.stardog.com/getting-support/) on how to get in touch to report a problem.
